// <auto-generated />
using EF_CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_CodeFirst.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "Ilica 25, Zagreb",
                            CompanyName = "Komunalac d.o.o.",
                            Designation = "Profesionalni upravljač kamionom",
                            Name = "Stipan Ljudevit Drmić"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "Ilica 26, Zagreb",
                            CompanyName = "Komunalac d.o.o.",
                            Designation = "Profesionalni upravljač kamionom",
                            Name = "Stipan"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "Ilica 25, Zagreb",
                            CompanyName = "Komunalac d.o.o.",
                            Designation = "Profesionalni upravljač kamionom",
                            Name = "Ljudevit Drmić"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Address = "Ščitarjevo 12",
                            Name = "Branko Radoš"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
